//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Guide.
        /// </summary>
        public static string AccountGuide {
            get {
                return ResourceManager.GetString("AccountGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Cannot be deleted please delete chilldren first.
        /// </summary>
        public static string CannotDeleteParent {
            get {
                return ResourceManager.GetString("CannotDeleteParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Guide Is Required.
        /// </summary>
        public static string ChartOfAccountAccountGuideRequired {
            get {
                return ResourceManager.GetString("ChartOfAccountAccountGuideRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code max length 100 characters.
        /// </summary>
        public static string ChartOfAccountCodeMaxLengthValidation {
            get {
                return ResourceManager.GetString("ChartOfAccountCodeMaxLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string ChartOfAccountCodeRequired {
            get {
                return ResourceManager.GetString("ChartOfAccountCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Valid Account Nature.
        /// </summary>
        public static string ChartOfAccountNotValidAccountNature {
            get {
                return ResourceManager.GetString("ChartOfAccountNotValidAccountNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of account with same code is existed.
        /// </summary>
        public static string ChartOfAccoutWithSameCodeExist {
            get {
                return ResourceManager.GetString("ChartOfAccoutWithSameCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default currency must be active.
        /// </summary>
        public static string CurrencyActiveOnDefault {
            get {
                return ResourceManager.GetString("CurrencyActiveOnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currency with same symbol is existed.
        /// </summary>
        public static string CurrencySymbolIsExisted {
            get {
                return ResourceManager.GetString("CurrencySymbolIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currency symbol can&apos;t exceed 4 letters.
        /// </summary>
        public static string CurrencySymbolMaxLength {
            get {
                return ResourceManager.GetString("CurrencySymbolMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default currency is already exited with name.
        /// </summary>
        public static string DefaultCurrencyIsAlreadyExitedWithName {
            get {
                return ResourceManager.GetString("DefaultCurrencyIsAlreadyExitedWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchage rate must be 1 for default currency.
        /// </summary>
        public static string ExchageRateOnDefaultCurrency {
            get {
                return ResourceManager.GetString("ExchageRateOnDefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate Is Required.
        /// </summary>
        public static string ExchangeRateIsRequired {
            get {
                return ResourceManager.GetString("ExchangeRateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل التحويل مطلوب.
        /// </summary>
        public static string ExchangeRateIsRequired1 {
            get {
                return ResourceManager.GetString("ExchangeRateIsRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name is required.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name can&apos;t exceed 50 letters.
        /// </summary>
        public static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name second language is required.
        /// </summary>
        public static string NameSecondLanguageIsRequired {
            get {
                return ResourceManager.GetString("NameSecondLanguageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name second language can&apos;t exceed 50 letters.
        /// </summary>
        public static string NameSecondLanguageMaxLength {
            get {
                return ResourceManager.GetString("NameSecondLanguageMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully.
        /// </summary>
        public static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with same name is existed.
        /// </summary>
        public static string WithSameNameIsExisted {
            get {
                return ResourceManager.GetString("WithSameNameIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with same name second language is existed.
        /// </summary>
        public static string WithSameNameSecondLanguageIsExisted {
            get {
                return ResourceManager.GetString("WithSameNameSecondLanguageIsExisted", resourceCulture);
            }
        }
    }
}
